name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Start Karma server
      run: karma start

    - name: Run tests
      run: npm test -- --single-run

    outputs:
      test-success: ${{ success() }}

  merge:
    needs: build
    if: ${{ needs.build.outputs.test-success == 'true' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Merge pull request
      run: git merge --no-ff

